import React, { useState, useEffect } from 'react';
import { User } from 'firebase/auth';
import { UserRole, UserProfile } from '../types/core';
import { CalendarEvent } from '../types/academic';
import * as CalendarService from '../services/db/calendar';
import { XIcon, ChevronLeftIcon, ChevronRightIcon, PlusIcon } from './icons';

// Local UI extension of CalendarEvent for internal use
interface CalendarEventUI extends CalendarEvent {
    // Derived properties for UI mapped from startDate/endDate
    start: string;
    end: string;
    color?: string; // UI only
}

interface CalendarManagerProps {
    user: User;
    userProfile: UserProfile | null;
    selectedSchoolId?: string; // Optional prop for context override
    onClose: () => void;
}

const EVENT_TYPES = ['Holiday', 'Exam', 'Activity', 'Suspension', 'Meeting', 'Deadline'];

export const CalendarManager = ({ user, userProfile, selectedSchoolId, onClose }: CalendarManagerProps) => {
    // Data State
    const [events, setEvents] = useState<CalendarEventUI[]>([]);
    const [isLoading, setIsLoading] = useState(true);

    // UI State
    const [currentDate, setCurrentDate] = useState(new Date());
    const [isModalOpen, setIsModalOpen] = useState(false);

    // Form State
    const [selectedDate, setSelectedDate] = useState<string>('');
    const [newEvent, setNewEvent] = useState<Partial<CalendarEvent>>({
        title: '',
        type: 'Activity',
        description: '',
        startDate: '',
        endDate: ''
    });

    // Derived state: Use prop override if available, otherwise profile
    const effectiveSchoolId = selectedSchoolId || userProfile?.schoolId;

    useEffect(() => {
        if (effectiveSchoolId) {
            loadData();
        } else {
            setIsLoading(false);
        }
    }, [effectiveSchoolId]);

    const loadData = async () => {
        if (!effectiveSchoolId) return;
        setIsLoading(true);
        try {
            const data = await CalendarService.loadEvents(effectiveSchoolId);
            // Map data to UI format
            const uiEvents: CalendarEventUI[] = data.map(evt => ({
                ...evt,
                start: evt.startDate,
                end: evt.endDate || evt.startDate,
                color: getEventColor(evt.type)
            }));
            setEvents(uiEvents);
        } catch (error) {
            console.error("Failed to load events", error);
        } finally {
            setIsLoading(false);
        }
    };

    const getEventColor = (type: string) => {
        switch (type) {
            case 'Exam': return '#ef4444'; // Red
            case 'Holiday': return '#f59e0b'; // Amber
            case 'Suspension': return '#7f1d1d'; // Dark Red
            case 'Meeting': return '#3b82f6'; // Blue
            case 'Deadline': return '#db2777'; // Pink
            default: return '#10b981'; // Green (Activity)
        }
    };

    const handleDateClick = (day: number) => {
        const dateStr = `${currentDate.getFullYear()}-${String(currentDate.getMonth() + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        setSelectedDate(dateStr);
        setNewEvent({
            title: '',
            type: 'Activity',
            description: '',
            startDate: dateStr,
            endDate: dateStr,
            targetAudience: 'All'
        });
        setIsModalOpen(true);
    };

    const handleSaveEvent = async () => {
        let targetSchoolId = effectiveSchoolId;

        // Allow Admins to create Global Events if no specific school is selected
        if (!targetSchoolId) {
            const role = userProfile?.role as string;
            if (role === 'admin' || role === 'super_admin') {
                targetSchoolId = 'Global';
            } else {
                console.error("Missing School ID", userProfile);
                alert("System Error: Your account is not associated with a valid School ID.");
                return;
            }
        }

        console.log("Saving Event Payload:", { targetSchoolId, newEvent });

        if (!newEvent.title) {
            alert("Please enter an Event Title.");
            return;
        }
        if (!newEvent.startDate) {
            alert("Please select a Start Date.");
            return;
        }

        setIsLoading(true);
        try {
            await CalendarService.saveEvent(targetSchoolId, {
                id: '', // Generated by service
                title: newEvent.title,
                description: newEvent.description || '',
                startDate: newEvent.startDate,
                endDate: newEvent.endDate || newEvent.startDate,
                type: newEvent.type as any,
                schoolId: targetSchoolId,
                createdBy: user.uid,
                createdAt: Date.now(),
                isOfficial: true,
                targetAudience: newEvent.targetAudience as any || 'All'
            });
            setIsModalOpen(false);
            await loadData();
        } catch (error: any) {
            console.error("Failed to save event", error);
            alert(`Failed to save event: ${error.message || 'Unknown error'}`);
        } finally {
            setIsLoading(false);
        }
    };

    // Calendar Navigation
    const daysInMonth = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 0).getDate();
    const firstDayOfMonth = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1).getDay(); // 0 = Sun
    const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

    const prevMonth = () => setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1));
    const nextMonth = () => setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1));

    const getEventsForDate = (day: number): CalendarEventUI[] => {
        const dateStr = `${currentDate.getFullYear()}-${String(currentDate.getMonth() + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
        return events.filter(e => e.start <= dateStr && e.end >= dateStr);
    };

    const handleDeleteEvent = async (eventId: string) => {
        if (!confirm("Are you sure you want to delete this event?")) return;

        setIsLoading(true);
        try {
            await CalendarService.deleteEvent(eventId);
            await loadData();
        } catch (error: any) {
            console.error("Failed to delete event", error);
            alert(`Failed to delete event: ${error.message || 'Unknown error'}`);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="bg-white dark:bg-slate-800 h-full flex flex-col relative">
            {/* Header */}
            <div className="p-6 border-b border-slate-200 dark:border-slate-700 flex justify-between items-center">
                <div>
                    <h2 className="text-2xl font-bold text-slate-800 dark:text-white">School Calendar</h2>
                    <p className="text-slate-500 dark:text-slate-400">Manage Events & Activities</p>
                </div>
                <button onClick={onClose} className="p-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 rounded-lg">
                    <XIcon className="w-6 h-6" />
                </button>
            </div>

            <div className="flex-1 flex overflow-hidden">
                {/* Sidebar Events List */}
                <div className="w-80 border-r border-slate-200 dark:border-slate-700 p-4 overflow-y-auto hidden md:block">
                    <h3 className="font-bold text-slate-700 dark:text-slate-300 mb-4">Upcoming Events</h3>
                    <div className="space-y-3">
                        {events.length === 0 && <p className="text-slate-400 text-sm">No events scheduled.</p>}
                        {events.sort((a, b) => a.start.localeCompare(b.start)).map((evt) => (
                            <div key={evt.id} className="p-3 bg-slate-50 dark:bg-slate-700/50 rounded-lg border border-slate-100 dark:border-slate-700 group relative">
                                <div className="font-medium text-slate-800 dark:text-slate-200 pr-6">{evt.title}</div>
                                <div className="text-xs text-slate-500">{evt.start} - {evt.end}</div>
                                <div className="mt-1 flex gap-2">
                                    <span className={`text-[10px] px-2 py-0.5 rounded-full text-white`} style={{ backgroundColor: evt.color }}>
                                        {evt.type}
                                    </span>
                                </div>
                                <button
                                    onClick={(e) => { e.stopPropagation(); handleDeleteEvent(evt.id!); }}
                                    className="absolute top-2 right-2 p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-colors opacity-0 group-hover:opacity-100"
                                    title="Delete Event"
                                >
                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
                                </button>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Main Calendar Area */}
                {/* Main Calendar Area */}
                <div className="flex-1 flex flex-col p-6 overflow-y-auto min-h-0 scrollbar-thin scrollbar-thumb-slate-300 dark:scrollbar-thumb-slate-600 pb-20"> {/* Added min-h-0 and scrollbar styles */}
                    <div className="flex justify-between items-center mb-6">
                        <h3 className="text-xl font-bold text-slate-700 dark:text-slate-200">
                            {monthNames[currentDate.getMonth()]} {currentDate.getFullYear()}
                        </h3>
                        <div className="flex gap-2">
                            <button onClick={prevMonth} className="p-2 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg">
                                <ChevronLeftIcon className="w-5 h-5" />
                            </button>
                            <button onClick={nextMonth} className="p-2 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg">
                                <ChevronRightIcon className="w-5 h-5" />
                            </button>
                        </div>
                    </div>

                    {/* Removed overflow-hidden to prevent clipping, kept border-radius via wrapper if needed, 
                        but simply removing overflow-hidden allows cells to render fully if they exceed container */}
                    <div className="grid grid-cols-7 gap-px bg-slate-200 dark:bg-slate-700 border border-slate-200 dark:border-slate-700 rounded-lg flex-1">
                        {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(day => (
                            <div key={day} className="bg-slate-50 dark:bg-slate-800 p-2 text-center text-xs font-bold text-slate-500 uppercase tracking-wider">
                                {day}
                            </div>
                        ))}

                        {Array.from({ length: firstDayOfMonth }).map((_, i) => (
                            <div key={`empty-${i}`} className="bg-white dark:bg-slate-800 min-h-[100px]" />
                        ))}

                        {Array.from({ length: daysInMonth }).map((_, i) => {
                            const day = i + 1;
                            const dayEvents = getEventsForDate(day);
                            return (
                                <div
                                    key={day}
                                    onClick={() => handleDateClick(day)}
                                    className="bg-white dark:bg-slate-800 p-2 min-h-[100px] hover:bg-indigo-50 dark:hover:bg-indigo-900/20 transition-colors cursor-pointer group relative"
                                >
                                    <span className="text-sm font-medium text-slate-700 dark:text-slate-300">{day}</span>
                                    <div className="mt-1 space-y-1">
                                        {dayEvents.map((evt, idx) => (
                                            <div key={idx} className="text-[10px] px-1 py-0.5 rounded truncate text-white" style={{ backgroundColor: evt.color }}>
                                                {evt.title}
                                            </div>
                                        ))}
                                    </div>
                                    {/* Hover Add Indicator */}
                                    <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                        <PlusIcon className="w-4 h-4 text-indigo-400" />
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>
            </div>

            {/* Event Modal */}
            {isModalOpen && (
                <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
                    <div className="bg-white dark:bg-slate-800 rounded-xl shadow-xl w-full max-w-md border border-slate-200 dark:border-slate-700 flex flex-col max-h-[90vh]">
                        <div className="p-4 border-b border-slate-200 dark:border-slate-700 flex justify-between items-center">
                            <h3 className="text-lg font-bold text-slate-800 dark:text-white">Add Event</h3>
                            <button onClick={() => setIsModalOpen(false)} className="text-slate-400 hover:text-slate-600">
                                <XIcon className="w-5 h-5" />
                            </button>
                        </div>

                        <div className="p-4 space-y-4 overflow-y-auto">
                            <div>
                                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Event Title</label>
                                <input
                                    type="text"
                                    className="w-full p-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-slate-900 dark:text-white"
                                    placeholder="e.g., Quarterly Exam"
                                    value={newEvent.title}
                                    onChange={(e) => setNewEvent({ ...newEvent, title: e.target.value })}
                                />
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Type</label>
                                    <select
                                        className="w-full p-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-slate-900 dark:text-white"
                                        value={newEvent.type}
                                        onChange={(e) => setNewEvent({ ...newEvent, type: e.target.value as any })}
                                    >
                                        {EVENT_TYPES.map(t => <option key={t} value={t}>{t}</option>)}
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Start Date</label>
                                    <input
                                        type="date"
                                        className="w-full p-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-slate-900 dark:text-white"
                                        value={newEvent.startDate}
                                        onChange={(e) => setNewEvent({ ...newEvent, startDate: e.target.value })}
                                    />
                                </div>
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">End Date</label>
                                    <input
                                        type="date"
                                        className="w-full p-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-slate-900 dark:text-white"
                                        value={newEvent.endDate}
                                        onChange={(e) => setNewEvent({ ...newEvent, endDate: e.target.value })}
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Audience</label>
                                    <select
                                        className="w-full p-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-slate-900 dark:text-white text-sm"
                                        value={newEvent.targetAudience || 'All'}
                                        onChange={(e) => setNewEvent({ ...newEvent, targetAudience: e.target.value as any })}
                                    >
                                        <option value="All">All</option>
                                        <option value="Teachers">Teachers Only</option>
                                        <option value="Students">Students Only</option>
                                    </select>
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">Description</label>
                                <textarea
                                    className="w-full p-2 rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 text-slate-900 dark:text-white"
                                    rows={3}
                                    placeholder="Additional details..."
                                    value={newEvent.description}
                                    onChange={(e) => setNewEvent({ ...newEvent, description: e.target.value })}
                                />
                            </div>
                        </div>

                        <div className="p-4 border-t border-slate-200 dark:border-slate-700 flex justify-end gap-2">
                            <button
                                onClick={() => setIsModalOpen(false)}
                                className="px-4 py-2 text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-lg transition-colors"
                            >
                                Cancel
                            </button>
                            <button
                                onClick={handleSaveEvent}
                                disabled={isLoading}
                                className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg transition-colors disabled:opacity-50"
                            >
                                {isLoading ? 'Saving...' : 'Save Event'}
                            </button>
                        </div>
                    </div>
                </div>
            )}
            {/* Loading Overlay */}
            {isLoading && (
                <div className="absolute inset-0 z-[60] bg-white/50 dark:bg-slate-800/50 backdrop-blur-sm flex items-center justify-center animate-fade-in">
                    <div className="flex flex-col items-center gap-3">
                        <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-indigo-600"></div>
                        <p className="text-sm font-bold text-indigo-600">Loading Events...</p>
                    </div>
                </div>
            )}
        </div>
    );
};
